### ISSUE TITLE
UI - Save/Load

### ISSUE THREAD

**Issue by Morthiasik** [absent-cosmos/somnova-nanoreno-2018#17]
Frames not working properly (hovering, lack of frames for Save empty slots)

**Comment by BrianWestley** [comment]
Needs more details.
Need a method to reproduce the bugs.
Need a description of what "hovering" is "not working properly"

**Comment by Morthiasik** [comment]
These issues are directed to Aran, he knows what's up

**Comment by Aran-SSB** [comment]
Unfortunately, this would require a rewrite of how Ren'Py handles mouse input, as the event is currently only sent to an object and its children. The X which would ideally make the file become more transparent is a child of the frame, making it currently impossible to achieve this. The only way to get around this would be to make the frame per se a child of the X, which itself would result in all kinds of unintended hover behavior.
